### ISSUE TITLE
error in evaluating the argument 'x' in selecting a method for function 't': non-conformable arguments

### ISSUE THREAD

**Issue by Truman11Zeng** [LizaDarrous/lhcMR#4]
Hi~

I'm having some issues running lhcMR.

After successfully running merge_sumstats(), check it and I get this:
> head(df)
         RSID     BETA.x       SE.x   TSTAT.x    PVAL.x A1.x A2.x   N.x CHR
1: rs28469191 -0.0316396 0.04024291 -0.786216 0.4317412    C    T 24510   2
2: rs28446791 -0.0341257 0.04003844 -0.852323 0.3940346    G    C 24510   2
3:  rs4557010 -0.0377936 0.04002262 -0.944306 0.3450133    T    C 24510   2
4:  rs6732811 -0.0562041 0.04301737 -1.306540 0.1913675    C    G 24510   2
5: rs28433318 -0.0441247 0.04136741 -1.066650 0.2861282    T    C 24510   2
6: rs11900053 -0.0283776 0.03852285 -0.736643 0.4613393    T    C 24510   2
     POS     BETA.y       SE.y  TSTAT.y    PVAL.y A1.y A2.y   N.y       PIK
1: 29970 0.01175536 0.03936811 0.298601 0.7652445    C    T 24510 0.4157217
2: 30091 0.01302789 0.03945297 0.330213 0.7412389    G    C 24510 0.4218664
3: 30940 0.01582529 0.03947332 0.400911 0.6884856    T    C 24510 0.4176528
4: 31318 0.03606035 0.04198281 0.858931 0.3903784    C    G 24510 0.5066676
5: 31791 0.03618918 0.04195608 0.862549 0.3883854    T    C 24510 0.5108651
6: 36787 0.01611202 0.03946474 0.408264 0.6830801    T    C 24510 0.4132318
        SIGK M_LOCAL MAFUK10K MAFUKBB LEAD     LDSC    WEIGHT A1 A2
1: 0.2627921    5001   0.0804  0.0742    0 97.79507 0.1170331  C  T
2: 0.2619009    5001   0.0808  0.0741    0 98.10443 0.1166417  G  C
3: 0.2627138    5001   0.0807  0.0739    0 97.90625 0.1167806  T  C
4: 0.2391186    5001   0.0709  0.0649    0 95.48765 0.1186619  C  G
5: 0.2413575    5001   0.0715  0.0650    0 98.51951 0.1171511  T  C
6: 0.2630958    5001   0.0808  0.0741    0 97.90157 0.1168313  T  C

But when I try to proceed with the workflow by Calculating smart starting points for the likelihood optimisation like this:
> SP_list = calculate_SP(df,trait.names,run_ldsc=TRUE,run_MR=TRUE,hm3=hm3,ld=ld,nStep = 2,
                       SP_single=3,SP_pair=50,SNP_filter=10)
I get the following error:
> Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 't': non-conformable arguments

Do you think you could help me figure out what's causing this?
Tahnk you!

**Comment by LizaDarrous** [comment]
Hello,

I tried a re-run of the analysis to see if some changes have happened to the dependencies that are causing this error but I didn't run into the error. 
Up to which step in calculate_SP() are you reaching? What's the outcome on screen / log outcome and where does it stop? I know there are only two places the function t() is used, lines 103 and 116 in calculate_SP() so there must be something wrong with the output there. 
Although the head(df) contains all the needed columns, are they the right type (chr vs numeric?) 
Sorry I can't help further without more info..
