### ISSUE TITLE
Very large ayx estimate

### ISSUE THREAD

**Issue by anglixue** [LizaDarrous/lhcMR#7]
Hi Liza,

Thank you for providing this wonderful MR method to estimate the bi-directional and confounding.

I came across a scenario where `axy` is not significant but `ayx` is very large.

Here are the output:

```
                             piX          piY          h2X          h2Y
Parameter estimates 0.0007229491 0.0002933724 9.022506e-02 0.0165025702
SE-JK                         NA           NA 6.850663e-03 0.0044666360
Pval                          NA           NA 1.301376e-39 0.0002202067
                            tX          tY        axy         ayx          iXY
Parameter estimates 0.14873065 -0.07746589 0.04806321 0.999969114 0.0653700354
SE-JK               0.06544677  0.03715679 0.08368621 0.008556125 0.0185246172
Pval                0.02305368  0.03708400 0.56574691 0.000000000 0.0004174173
                          iX      iY
Parameter estimates 1.145369 1.04366
SE-JK                     NA      NA
Pval                      NA      NA
```

I used exactly the same settings in the sample code.
```
## Step 1
trait.names=c(exposure,outcome)
input.files = list(X,Y)
df = merge_sumstats(input.files,trait.names,LD.filepath,rho.filepath)

## Step 2
SP_list = calculate_SP(df,trait.names,run_ldsc=TRUE,run_MR=TRUE,hm3=hm3,ld=ld,nStep = 2,SP_single=3,SP_pair=50,SNP_filter=10)

## Step 3
res = lhc_mr(SP_list, trait.names, paral_method="lapply", nBlock=200)
```

I found it hard interpreting this result and wonder is that something wrong with my input? 

I also used other MR methods and the forward estimate is significant and around 0.2, and the reverse estimate is also significant and around 0.2.

Any comments is appreciated.

**Comment by LizaDarrous** [comment]
Hello,

Thank you for your interest inLHC-MR! 
From your results I can see that the direct heritability of the outcome Y is very small (< 2.5%) and the calculated total heritability for Y is also < 2.5% (tot_h2Y = h2Y + (tY + (axy*tX))^2 + h2X*axy^2), which is a limitations for LHC-MR. In the manuscript discussion we mention this, and how instrumenting traits with such a small heritability is questionable and can lead to un-interpretable results.

Best,
Liza
